/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';
/* OUTPUTCASHDESK */
export const GET_OUTPUT_CASH_DESK = 'GET_OUTPUT_CASH_DESK';
export const GET_OUTPUT_CASH_FOR_CUT = 'GET_OUTPUT_CASH_DESK_FOR_CUT';
export const GET_OUTPUT_CASH_FOR_CUT_AND_STATUS =
  'GET_OUTPUT_CASH_DESK_FOR_CUT_AND_STATUS';
export const ADD_OUTPUT_CASH_DESK = 'ADD_OUTPUT_CASH_DESK';
export const UPDATE_OUTPUT_CASH_DESK = 'UPDATE_OUTPUT_CASH_DESK';
export const REMOVE_OUTPUT_CASH_DESK = 'REMOVE_OUTPUT_CASH_DESK';
/* SALES FOR DATE */
export const GET_SALES_FOR_DATE_PAYMENT = 'GET_SALES_FOR_DATE_PAYMENT';
export const GET_SALES_FOR_DATE_CHANNELS = 'GET_SALES_FOR_DATE_CHANNELS';
export const GET_ALL_SALES_FOR_DATE = 'GET_ALL_SALES_FOR_DATE';
/* CASH DESK CLOSING */
export const GET_CASH_DESK_CLOSING = 'GET_CASH_DESK_CLOSING';
export const ADD_CASH_DESK_CLOSING = 'ADD_CASH_DESK_CLOSING';
export const UPDATE_PRETTY_CASH_DESK_CLOSING = 'UPDATE_PRETTY_CASH_DESK_CLOSING';
export const UPDATE_CASH_DESK_CLOSING = 'UPDATE_CASH_DESK_CLOSING';
export const REMOVE_CASH_DESK_CLOSING = 'REMOVE_OUTPUT_CASH_DESK';
export const START_CASH_DESK_CLOSING = 'START_CASH_DESK_CLOSING';


/* DISCOUNT */
export const GET_DISCOUNT = 'GET_DISCOUNT';
export const GET_DISCOUNT_FOR_ID = 'GET_DISCOUNT_FOR_ID';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';
export const REMOVE_DISCOUNT = 'REMOVE_DISCOUNT';
export const OPEN_FORM_DISCOUNT = 'OPEN_FORM_DISCOUNT';
export const CLOSE_FORM_DISCOUNT = 'CLOSE_FORM_DISCOUNT';
export const SEARCH_DISCOUNT = 'SEARCH_DISCOUNT';
export const ADD_BOOL_DISCOUNT = 'ADD_BOOL_DISCOUNT';
export const ADD_COUPON_DISCOUNT = 'ADD_COUPON_DISCOUNT';
/* CATEGORY */
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_FOR_ID = 'GET_CATEGORY_FOR_ID';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const ADD_BOOL = 'ADD_BOOL';
export const CLOSE_FORM_CATEGORY = 'CLOSE_FORM_CATEGORY';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';

/* SUBCATEGORY */
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const GET_SUBCATEGORY_FOR_ID = 'GET_SUBCATEGORY_FOR_ID';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY';
export const REMOVE_SUBCATEGORY = 'REMOVE_SUBCATEGORY';
export const OPEN_FORM_SUBCATEGORY = 'OPEN_FORM_SUBCATEGORY';
export const CLOSE_FORM_SUBCATEGORY = 'CLOSE_FORM_SUBCATEGORY';
export const SEARCH_SUBCATEGORY = 'SEARCH_SUBCATEGORY';

/* CHANNEL */
export const GET_CHANNEL = 'GET_CHANNEL';
export const GET_CHANNEL_FOR_ID = 'GET_CHANNEL_FOR_ID';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const OPEN_FORM_CHANNEL = 'OPEN_FORM_CHANNEL';
export const CLOSE_FORM_CHANNEL = 'CLOSE_FORM_CHANNEL';
export const SEARCH_CHANNEL = 'SEARCH_CHANNEL';

/* SUBCHANNEL */
export const GET_SUBCHANNEL = 'GET_SUBCHANNEL';
export const GET_SUBCHANNEL_FOR_ID = 'GET_SUBCHANNEL_FOR_ID';
export const ADD_SUBCHANNEL = 'ADD_SUBCHANNEL';
export const UPDATE_SUBCHANNEL = 'UPDATE_SUBCHANNEL';
export const REMOVE_SUBCHANNEL = 'REMOVE_SUBCHANNEL';
export const OPEN_FORM_SUBCHANNEL = 'OPEN_FORM_SUBCHANNEL';
export const CLOSE_FORM_SUBCHANNEL = 'CLOSE_FORM_SUBCHANNEL';
export const SEARCH_SUBCHANNEL = 'SEARCH_SUBCHANNEL';

/* PAYMENT_METHOD */
export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD';
export const GET_PAYMENT_METHOD_FOR_ID = 'GET_PAYMENT_METHOD_FOR_ID';
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD';
export const UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD';
export const REMOVE_PAYMENT_METHOD = 'REMOVE_PAYMENT_METHOD';
export const OPEN_FORM_PAYMENT_METHOD = 'OPEN_FORM_PAYMENT_METHOD';
export const CLOSE_FORM_PAYMENT_METHOD = 'CLOSE_FORM_PAYMENT_METHOD';
export const SEARCH_PAYMENT_METHOD = 'SEARCH_PAYMENT_METHOD';

/* PAYMENT_METHOD_DETAIL */
export const GET_PAYMENT_METHOD_DETAIL = 'GET_PAYMENT_METHOD_DETAIL';
export const GET_PAYMENT_METHOD_DETAIL_FOR_ID =
  'GET_PAYMENT_METHOD_DETAIL_FOR_ID';
export const ADD_PAYMENT_METHOD_DETAIL = 'ADD_PAYMENT_METHOD_DETAIL';
export const UPDATE_PAYMENT_METHOD_DETAIL = 'UPDATE_PAYMENT_METHOD_DETAIL';
export const REMOVE_PAYMENT_METHOD_DETAIL = 'REMOVE_PAYMENT_METHOD_DETAIL';
export const OPEN_FORM_PAYMENT_METHOD_DETAIL =
  'OPEN_FORM_PAYMENT_METHOD_DETAIL';
export const CLOSE_FORM_PAYMENT_METHOD_DETAIL =
  'CLOSE_FORM_PAYMENT_METHOD_DETAIL';
export const SEARCH_PAYMENT_METHOD_DETAIL = 'SEARCH_PAYMENT_METHOD_DETAIL';

/* USER */
export const GET_USER = 'GET_USER';
export const GET_USER_FOR_ID = 'GET_USER_FOR_ID';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const OPEN_FORM_USER = 'OPEN_FORM_USER';
export const CLOSE_FORM_USER = 'CLOSE_FORM_USER';
export const CLOSE_FORM_CODE = 'CLOSE_FORM_CODE';
export const SEARCH_USER = 'SEARCH_USER';

/* CUSTOMER */
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_FOR_ID = 'GET_CUSTOMER_FOR_ID';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const OPEN_FORM_CUSTOMER = 'OPEN_FORM_CUSTOMER';
export const CLOSE_FORM_CUSTOMER = 'CLOSE_FORM_CUSTOMER';
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const GET_ALL_CUSTOMER= 'GET_ALL_CUSTOMER';
export const SET_CUSTOMER = 'SET_CUSTOMER';

/* GIFCARD */
export const GET_GIFTCARD = 'GET_GIFTCARD';
export const GET_GIFTCARD_FOR_ID = 'GET_GIFTCARD_FOR_ID';
export const ADD_GIFTCARD = 'ADD_GIFTCARD';
export const UPDATE_GIFTCARD = 'UPDATE_GIFTCARD';
export const REMOVE_GIFTCARD = 'REMOVE_GIFTCARD';
export const OPEN_FORM_GIFTCARD = 'OPEN_FORM_GIFTCARD';
export const CLOSE_FORM_GIFTCARD = 'CLOSE_FORM_GIFTCARD';
export const SEARCH_GIFTCARD = 'SEARCH_GIFTCARD';

/* RESTAURANT */
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const GET_RESTAURANT_FOR_ID = 'GET_RESTAURANT_FOR_ID';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const REMOVE_RESTAURANT = 'REMOVE_RESTAURANT';
export const OPEN_FORM_RESTAURANT = 'OPEN_FORM_RESTAURANT';
export const CLOSE_FORM_RESTAURANT = 'CLOSE_FORM_RESTAURANT';
export const SEARCH_RESTAURANT = 'SEARCH_RESTAURANT';

/* BRAND */
export const GET_BRAND = 'GET_BRAND';

// EMPLOYEE
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_FOR_ID = 'GET_EMPLOYEE_FOR_ID';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const OPEN_FORM_EMPLOYEE = 'OPEN_FORM_EMPLOYEE';
export const CLOSE_FORM_EMPLOYEE = 'CLOSE_FORM_EMPLOYEE';
export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';

// Role
export const GET_ROLE = 'GET_ROLE';
export const GET_ROLE_FOR_ID = 'GET_ROLE_FOR_ID';
export const ADD_ROLE = 'ADD_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const REMOVE_ROLE = 'REMOVE_ROLE';
export const OPEN_FORM_ROLE = 'OPEN_FORM_ROLE';
export const CLOSE_FORM_ROLE = 'CLOSE_FORM_ROLE';
export const SEARCH_ROLE = 'SEARCH_ROLE';

// ROLE_DETAIL
export const GET_ROLE_DETAIL = 'GET_ROLE_DETAIL';
export const GET_ROLE_DETAIL_FOR_ID = 'GET_ROLE_DETAIL_FOR_ID';
export const ADD_ROLE_DETAIL = 'ADD_ROLE_DETAIL';
export const UPDATE_ROLE_DETAIL = 'UPDATE_ROLE_DETAIL';
export const REMOVE_ROLE_DETAIL = 'REMOVE_ROLE_DETAIL';
export const OPEN_FORM_ROLE_DETAIL = 'OPEN_FORM_ROLE_DETAIL';
export const CLOSE_FORM_ROLE_DETAIL = 'CLOSE_FORM_ROLE_DETAIL';
export const SEARCH_ROLE_DETAIL = 'SEARCH_ROLE_DETAIL';

// ROLE_DETAIL
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_FOR_ID = 'GET_ARTICLE_FOR_ID';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const OPEN_FORM_ARTICLE = 'OPEN_FORM_ARTICLE';
export const CLOSE_FORM_ARTICLE = 'CLOSE_FORM_ARTICLE';
export const SEARCH_ARTICLE = 'SEARCH_ARTICLE';

// RECIPE
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_FOR_ID = 'GET_RECIPE_FOR_ID';
export const ADD_RECIPE = 'ADD_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const OPEN_FORM_RECIPE = 'OPEN_FORM_RECIPE';
export const CLOSE_FORM_RECIPE = 'CLOSE_FORM_RECIPE';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';

// BUTTON
export const GET_BUTTON = 'GET_BUTTON';
export const GET_BUTTON_FOR_ID = 'GET_BUTTON_FOR_ID';
export const ADD_BUTTON = 'ADD_BUTTON';
export const UPDATE_BUTTON = 'UPDATE_BUTTON';
export const REMOVE_BUTTON = 'REMOVE_BUTTON';
export const OPEN_FORM_BUTTON = 'OPEN_FORM_BUTTON';
export const CLOSE_FORM_BUTTON = 'CLOSE_FORM_BUTTON';
export const SEARCH_BUTTON = 'SEARCH_BUTTON';

// PRODUCT_DETAIL
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_FOR_ID = 'GET_PRODUCT_DETAIL_FOR_ID';
export const ADD_PRODUCT_DETAIL = 'ADD_PRODUCT_DETAIL';
export const UPDATE_PRODUCT_DETAIL = 'UPDATE_PRODUCT_DETAIL';
export const REMOVE_PRODUCT_DETAIL = 'REMOVE_PRODUCT_DETAIL';
export const OPEN_FORM_PRODUCT_DETAIL = 'OPEN_FORM_PRODUCT_DETAIL';
export const CLOSE_FORM_PRODUCT_DETAIL = 'CLOSE_FORM_PRODUCT_DETAIL';
export const SEARCH_PRODUCT_DETAIL = 'SEARCH_PRODUCT_DETAIL';

// PRODUCT
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_FOR_ID = 'GET_PRODUCT_FOR_ID';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const OPEN_FORM_PRODUCT = 'OPEN_FORM_PRODUCT';
export const CLOSE_FORM_PRODUCT = 'CLOSE_FORM_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

// RECIPE_ARTICLE
export const GET_RECIPE_ARTICLE = 'GET_RECIPE_ARTICLE';
export const GET_RECIPE_ARTICLE_FOR_ID = 'GET_RECIPE_ARTICLE_FOR_ID';
export const ADD_RECIPE_ARTICLE = 'ADD_RECIPE_ARTICLE';
export const UPDATE_RECIPE_ARTICLE = 'UPDATE_RECIPE_ARTICLE';
export const REMOVE_RECIPE_ARTICLE = 'REMOVE_RECIPE_ARTICLE';
export const OPEN_FORM_RECIPE_ARTICLE = 'OPEN_FORM_RECIPE_ARTICLE';
export const CLOSE_FORM_RECIPE_ARTICLE = 'CLOSE_FORM_RECIPE_ARTICLE';
export const SEARCH_RECIPE_ARTICLE = 'SEARCH_RECIPE_ARTICLE';

// CATEGORY_BUTTON
export const GET_CATEGORY_BUTTON = 'GET_CATEGORY_BUTTON';
export const GET_CATEGORY_BUTTON_FOR_ID = 'GET_CATEGORY_BUTTON_FOR_ID';
export const ADD_CATEGORY_BUTTON = 'ADD_CATEGORY_BUTTON';
export const UPDATE_CATEGORY_BUTTON = 'UPDATE_CATEGORY_BUTTON';
export const REMOVE_CATEGORY_BUTTON = 'REMOVE_CATEGORY_BUTTON';
export const OPEN_FORM_CATEGORY_BUTTON = 'OPEN_FORM_CATEGORY_BUTTON';
export const CLOSE_FORM_CATEGORY_BUTTON = 'CLOSE_FORM_CATEGORY_BUTTON';
export const SEARCH_CATEGORY_BUTTON = 'SEARCH_CATEGORY_BUTTON';

// OPTIONAL
export const GET_OPTIONAL = 'GET_OPTIONAL';
export const GET_OPTIONAL_FOR_ID = 'GET_OPTIONAL_FOR_ID';
export const ADD_OPTIONAL = 'ADD_OPTIONAL';
export const UPDATE_OPTIONAL = 'UPDATE_OPTIONAL';
export const REMOVE_OPTIONAL = 'REMOVE_OPTIONAL';
export const OPEN_FORM_OPTIONAL = 'OPEN_FORM_OPTIONAL';
export const CLOSE_FORM_OPTIONAL = 'CLOSE_FORM_OPTIONAL';
export const SEARCH_OPTIONAL = 'SEARCH_OPTIONAL';

// OPTIONAL_PRODUCT
export const GET_OPTIONAL_PRODUCT = 'GET_OPTIONAL_PRODUCT';
export const GET_OPTIONAL_PRODUCT_FOR_ID = 'GET_OPTIONAL_PRODUCT_FOR_ID';
export const ADD_OPTIONAL_PRODUCT = 'ADD_OPTIONAL_PRODUCT';
export const UPDATE_OPTIONAL_PRODUCT = 'UPDATE_OPTIONAL_PRODUCT';
export const REMOVE_OPTIONAL_PRODUCT = 'REMOVE_OPTIONAL_PRODUCT';
export const OPEN_FORM_OPTIONAL_PRODUCT = 'OPEN_FORM_OPTIONAL_PRODUCT';
export const CLOSE_FORM_OPTIONAL_PRODUCT = 'CLOSE_FORM_OPTIONAL_PRODUCT';
export const SEARCH_OPTIONAL_PRODUCT = 'SEARCH_OPTIONAL_PRODUCT';

// DOCUMENT_TYPE
export const GET_DOCUMENT_TYPE = 'GET_DOCUMENT_TYPE';
export const GET_DOCUMENT_TYPE_FOR_ID = 'GET_DOCUMENT_TYPE_FOR_ID';
export const ADD_DOCUMENT_TYPE = 'ADD_DOCUMENT_TYPE';
export const UPDATE_DOCUMENT_TYPE = 'UPDATE_DOCUMENT_TYPE';
export const REMOVE_DOCUMENT_TYPE = 'REMOVE_DOCUMENT_TYPE';
export const OPEN_FORM_DOCUMENT_TYPE = 'OPEN_FORM_DOCUMENT_TYPE';
export const CLOSE_FORM_DOCUMENT_TYPE = 'CLOSE_FORM_DOCUMENT_TYPE';
export const SEARCH_DOCUMENT_TYPE = 'SEARCH_DOCUMENT_TYPE';

// DOCUMENT
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_FOR_ID = 'GET_DOCUMENT_FOR_ID';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';
export const OPEN_FORM_DOCUMENT = 'OPEN_FORM_DOCUMENT';
export const CLOSE_FORM_DOCUMENT = 'CLOSE_FORM_DOCUMENT';
export const SEARCH_DOCUMENT = 'SEARCH_DOCUMENT';
export const GET_DOCUMENT_FOR_TYPE = 'GET_DOCUMENT_FOR_TYPE';
export const GET_ALL_DOCUMENTS = 'GET_ALL_DOCUMENTS';

// BUTTON_DETAIL
export const GET_BUTTON_DETAIL = 'GET_BUTTON_DETAIL';
export const GET_BUTTON_DETAIL_FOR_ID = 'GET_BUTTON_DETAIL_FOR_ID';
export const ADD_BUTTON_DETAIL = 'ADD_BUTTON_DETAIL';
export const UPDATE_BUTTON_DETAIL = 'UPDATE_BUTTON_DETAIL';
export const REMOVE_BUTTON_DETAIL = 'REMOVE_BUTTON_DETAIL';
export const OPEN_FORM_BUTTON_DETAIL = 'OPEN_FORM_BUTTON_DETAIL';
export const CLOSE_FORM_BUTTON_DETAIL = 'CLOSE_FORM_BUTTON_DETAIL';
export const SEARCH_BUTTON_DETAIL = 'SEARCH_BUTTON_DETAIL';

// PRICES
export const GET_PRICE = 'GET_PRICE';
export const GET_PRICE_FOR_ID = 'GET_PRICE_FOR_ID';
export const ADD_PRICE = 'ADD_PRICE';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const REMOVE_PRICE = 'REMOVE_PRICE';
export const OPEN_FORM_PRICE = 'OPEN_FORM_PRICE';
export const CLOSE_FORM_PRICE = 'CLOSE_FORM_PRICE';
export const SEARCH_PRICE = 'SEARCH_PRICE';

// MODIFIERS
export const GET_MODIFIER = 'GET_MODIFIER';
export const GET_MODIFIER_FOR_ID = 'GET_MODIFIER_FOR_ID';
export const ADD_MODIFIER = 'ADD_MODIFIER';
export const UPDATE_MODIFIER = 'UPDATE_MODIFIER';
export const REMOVE_MODIFIER = 'REMOVE_MODIFIER';
export const OPEN_FORM_MODIFIER = 'OPEN_FORM_MODIFIER';
export const CLOSE_FORM_MODIFIER = 'CLOSE_FORM_MODIFIER';
export const SEARCH_MODIFIER = 'SEARCH_MODIFIER';

// MODIFIER_PRODUCTS
export const GET_MODIFIER_PRODUCT = 'GET_MODIFIER_PRODUCT';
export const GET_MODIFIER_PRODUCT_FOR_ID = 'GET_MODIFIER_PRODUCT_FOR_ID';
export const ADD_MODIFIER_PRODUCT = 'ADD_MODIFIER_PRODUCT';
export const UPDATE_MODIFIER_PRODUCT = 'UPDATE_MODIFIER_PRODUCT';
export const REMOVE_MODIFIER_PRODUCT = 'REMOVE_MODIFIER_PRODUCT';
export const OPEN_FORM_MODIFIER_PRODUCT = 'OPEN_FORM_MODIFIER_PRODUCT';
export const CLOSE_FORM_MODIFIER_PRODUCT = 'CLOSE_FORM_MODIFIER_PRODUCT';
export const SEARCH_MODIFIER_PRODUCT = 'SEARCH_MODIFIER_PRODUCT';

// SUBMODIFIERS
export const GET_SUBMODIFIER = 'GET_SUBMODIFIER';
export const GET_SUBMODIFIER_FOR_ID = 'GET_SUBMODIFIER_FOR_ID';
export const ADD_SUBMODIFIER = 'ADD_SUBMODIFIER';
export const UPDATE_SUBMODIFIER = 'UPDATE_SUBMODIFIER';
export const REMOVE_SUBMODIFIER = 'REMOVE_SUBMODIFIER';
export const OPEN_FORM_SUBMODIFIER = 'OPEN_FORM_SUBMODIFIER';
export const CLOSE_FORM_SUBMODIFIER = 'CLOSE_FORM_SUBMODIFIER';
export const SEARCH_SUBMODIFIER = 'SEARCH_SUBMODIFIER';

// SUBMODIFIERS
export const GET_DEPMODIFIER = 'GET_DEPMODIFIER';
export const GET_DEPMODIFIER_FOR_ID = 'GET_DEPMODIFIER_FOR_ID';
export const ADD_DEPMODIFIER = 'ADD_DEPMODIFIER';
export const UPDATE_DEPMODIFIER = 'UPDATE_DEPMODIFIER';
export const REMOVE_DEPMODIFIER = 'REMOVE_DEPMODIFIER';
export const OPEN_FORM_DEPMODIFIER = 'OPEN_FORM_DEPMODIFIER';
export const CLOSE_FORM_DEPMODIFIER = 'CLOSE_FORM_DEPMODIFIER';
export const SEARCH_DEPMODIFIER = 'SEARCH_DEPMODIFIER';

// TIKET_CONFIGURATION
export const GET_TIKET_CONFIGURATION = 'GET_TIKET_CONFIGURATION';
export const ADD_TIKET_CONFIGURATION = 'ADD_TIKET_CONFIGURATION';
export const UPDATE_TIKET_CONFIGURATION = 'UPDATE_TIKET_CONFIGURATION';
export const OPEN_FORM_TIKET_CONFIGURATION = 'OPEN_FORM_TIKET_CONFIGURATION';
export const CLOSE_FORM_TIKET_CONFIGURATION = 'CLOSE_FORM_TIKET_CONFIGURATION';

// TIKET_CONFIGURATION
export const ADD_CANCELED_SALE = 'ADD_CANCELED_SALE';

// SALES
export const GET_SALE = 'GET_SALE';
export const ADD_SALE = 'ADD_SALE';
export const UPDATE_SALE = 'UPDATE_SALE';
export const OPEN_FORM_SALE = 'OPEN_FORM_SALE';
export const CLOSE_FORM_SALE = 'CLOSE_FORM_SALE';
export const REMOVE_SALE = 'REMOVE_SALE';
export const SEARCH_SALE = 'SEARCH_SALE';

// auth
export const POST_AUTH_USER = 'POST_AUTH_USER';
export const SET_AUTH_USER = 'SET_AUTH_USER';

// CUSTOMER_SALES

export const GET_CUSTOMER_SALES = 'GET_CUSTOMER_SALES';
export const CUSTOMER_SALES_CHANGE_CHANNEL = 'CUSTOMER_SALES_CHANGE_CHANNEL';
export const CUSTOMER_SALES_CHANGE_SUBCHANNEL =
  'CUSTOMER_SALES_CHANGE_SUBCHANNEL';
export const CUSTOMER_SALES_GET_CHANNEL = 'CUSTOMER_SALES_GET_CHANNEL';
export const CHANGE_SUBCATEGORY_CUSTOMER_SALES =
  'CHANGE_SUBCATEGORY_CUSTOMER_SALES';
export const GET_ALL_CUSTOMER_SALES = 'GET_ALL_CUSTOMER_SALES';
export const CHANGE_STATUS_MODIFIER_MODAL = 'CHANGE_STATUS_MODIFIER_MODAL';
export const CHANGE_MODIFIER_SELECTED = 'CHANGE_MODIFIER_SELECTED';
export const CHANGE_MODIFIER_STEP = 'CHANGE_MODIFIER_STEP';
export const SET_SUBMODIFIER_LIST_CUSTOMER_SALES =
  'SET_SUBMODIFIER_LIST_CUSTOMER_SALES';
export const SET_CATEGORY_CUSTOMER_SALES = 'SET_CATEGORY_CUSTOMER_SALES';
export const SET_PRODUCT_CUSTOMER_SALE = 'SET_PRODUCT_CUSTOMER_SALE'
export const SET_LEVEL_CUSTOMER_SALE = 'SET_LEVEL_CUSTOMER_SALE';
export const SET_MODIFIER_SELECT_ID_CUSTOMER_SALES = 'SET_MODIFIER_SELECT_ID_CUSTOMER_SALES'
export const SET_SUBMODIFIER_SELECT_ID_CUSTOMER_SALES = 'SET_SUBMODIFIER_SELECT_ID_CUSTOMER_SALES';
export const SET_DEPMODIFIER_SELECT_ID_CUSTOMER_SALES = 'SET_DEPMODIFIER_SELECT_ID_CUSTOMER_SALES';
export const ADD_ORDER_CUSTOMER_SALES = 'ADD_ORDER_CUSTOMER_SALES';
export const SET_PRICE_SELECTED_CUSTOMER_SALES = 'SET_PRICE_SELECTED_CUSTOMER_SALES';
export const ADD_PRODUCT_CUSTOMER_SALES = 'ADD_PRODUCT_CUSTOMER_SALES';
export const DELETE_PRODUCT_CUSTOMER_SALES = 'DELETE_PRODUCT_CUSTOMER_SALES';
export const UPDATE_PRODUCT_CUSTOMER_SALES = 'UPDATE_PRODUCT_CUSTOMER_SALES';
export const SET_IDENTIFIER_PRODUCT_CUSTOMER_SALES = 'SET_IDENTIFIER_PRODUCT_CUSTOMER_SALES';
export const ADD_MODIFIER_PRODUCT_CUSTOMER_SALES = 'ADD_MODIFIER_PRODUCT_CUSTOMER_SALES';
export const SET_CLIENT_MODAL_CUSTOMER_SALES = 'SET_CLIENT_MODAL_CUSTOMER_SALES';
export const SET_DOCUMENT_MODAL_CUSTOMER_SALES = 'SET_DOCUMENT_MODAL_CUSTOMER_SALES';
export const SET_DOCUMENT_CUSTOMER_SALES = 'SET_DOCUMENT_CUSTOMER_SALES';
export const SET_CUSTOMER_CUSTOMER_SALES = 'SET_CUSTOMER_CUSTOMER_SALES'; 
export const SET_DOCUMENT_TYPE_CUSTOMER_SALES = 'SET_DOCUMENT_TYPE_CUSTOMER_SALES'; 
export const SET_PAYMENT_METHOD_DETAIL_CUSTOMER_SALES = 'SET_PAYMENT_METHOD_DETAIL_CUSTOMER_SALES';
export const SET_PAYMENT_METHOD_CUSTOMER_SALES = 'SET_PAYMENT_METHOD_CUSTOMER_SALES';
export const READ_CASH_DESK_CLOSING_FOR_DATE_DESK_STATU_CS = 'READ_CASH_DESK_CLOSING_FOR_DATE_DESK_STATU_CS';
export const SET_ORDER_CUSTOMER_SALES = 'SET_ORDER_CUSTOMER_SALES';
export const SET_STATUS_ORDER_CUSTOMER_SALES = 'SET_STATUS_ORDER_CUSTOMER_SALES';
export const SET_ORDER_MODAL_CUSTOMER_SALES = 'SET_ORDER_MODAL_CUSTOMER_SALES';
export const SET_ORDER_SELECTED_CUSTOMER_SALES = 'SET_ORDER_SELECTED_CUSTOMER_SALES';
export const SET_DISCOUNT_MODAL_CUSTOMER_SALES='SET_DISCOUNT_MODAL_CUSTOMER_SALES';
export const  SET_CLEAN_SELECT_DETAIL_CUSTOMER_SALES = 'SET_CLEAN_SELECT_DETAIL_CUSTOMER_SALES';
export const GET_CHANNEL_CUSTOMER_DETAIL = 'GET_CHANNEL_CUSTOMER_DETAIL';
export const SET_STATUS_SIDEBAR_CUSTOMER_DETAIL = 'SET_STATUS_SIDEBAR_CUSTOMER_DETAIL';
export const GET_PRICES_FOR_CHANNEL_AND_CATEGORY = 'GET_PRICES_FOR_CHANNEL_AND_CATEGORY';
export const SET_DESCRIPTION_CUSTOMER_SALES = 'SET_DESCRIPTION_CUSTOMER_SALES';
export const SET_SEARCH_CUSTOMER_SALES = 'SET_SEARCH_CUSTOMER_SALES';
export const SET_ORDER_DATA_CUSTOMER_SALES = 'SET_ORDER_DATA_CUSTOMER_SALES';
export const SET_IS_PRODUCT_MODIFIER_CLICK_CS = 'SET_IS_PRODUCT_MODIFIER_CLICK_CS';
export const SET_DISCOUNT_SUBCHANNEL_CUSTOMER_SALES = 'SET_DISCOUNT_SUBCHANNEL_CUSTOMER_SALES';

export const OPEN_CARD_FORM_SUBMODIFIER = 'OPEN_CARD_FORM_SUBMODIFIER';
export const CLOSE_CARD_FORM_SUBMODIFIER = 'CLOSE_CARD_FORM_SUBMODIFIER';
export const GET_ALL_CARD_SUBMODIFIER = 'GET_ALL_CARD_SUBMODIFIER';
export const SET_MODIFIER_SELECTED_ID_CM = 'SET_MODIFIER_SELECTED_ID_CM';
export const STATUS_PRODUCT_CARD_SUBMODIFIER =
  'STATUS_PRODUCT_CARD_SUBMODIFIER';

export const OPEN_CARD_FORM_DEPMODIFIER = 'OPEN_CARD_FORM_DEPMODIFIER';
export const CLOSE_CARD_FORM_DEPMODIFIER = 'CLOSE_CARD_FORM_DEPMODIFIER';
export const GET_ALL_CARD_DEPMODIFIER = 'GET_ALL_CARD_DEPMODIFIER';


// PRINTS
export const PRINT_TIKET = 'PRINT_TIKET';
export const PRINT_REPORT_CUT = 'PRINT_REPORT_CUT';
export const PRINT_CUT_X = 'PRINT_CUT_X'; 
export const GET_ALL_PRINT = 'GET_ALL_PRINT';
export const PRINT_CUT_Z = 'PRINT_CUT_Z';
export const PRINT_OUTPUT_CASH = 'PRINT_OUTPUT_CASH';